var GraphAPI = require('azure-graphapi');

const CLIENT_ID = '0d95b59b-378b-4e21-85fe-04e20ea8c748';
const CLIENT_SECRET = 'k6qFG6DDoDy5wxffj/pG8M70iPX+hHqsqFE3qXTiBV0=';
const AZURE_TENANT = 'isstrainerlive.onmicrosoft.com';
const ACCESS_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ilk0dWVLMm9hSU5RaVFiNVlFQlNZVnlEY3BBVSIsImtpZCI6Ilk0dWVLMm9hSU5RaVFiNVlFQlNZVnlEY3BBVSJ9.eyJhdWQiOiIwMDAwMDAwMi0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC81Yzg0ZGJkNy0yNTdiLTRjY2EtYjFmMS0yNzRkMDZjODI5MmEvIiwiaWF0IjoxNDg0ODY4MzgxLCJuYmYiOjE0ODQ4NjgzODEsImV4cCI6MTQ4NDg3MjI4MSwiYWNyIjoiMSIsImFpbyI6IkFRQUJBQUVBQUFEUk5ZUlEzZGhSU3JtLTRLLWFkcENKUW1VT3Y0bHMzczRhb2NUX0RVSDk5YWpfVW1lSjQ4SWZNTXlhOUx6eHVfM3F6YkpnOUg3bWt4M0Z3WDdwcF80cnpQMkNqVFNSTXlqWW5RQ1BZNnV6NU9zck9BNXRrOTFVeTJUN00yT3lUekVnQUEiLCJhbHRzZWNpZCI6IjU6OjEwMDNCRkZEOUJDMUYzMEEiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiMGQ5NWI1OWItMzc4Yi00ZTIxLTg1ZmUtMDRlMjBlYThjNzQ4IiwiYXBwaWRhY3IiOiIxIiwiZW1haWwiOiJqb2hubUBpc29mdHN0b25lLmNvbSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzI4MGE1YTM2LTQ1NjktNGMzMi05ZjExLWQ1NzU4NmU2MTlkMS8iLCJpcGFkZHIiOiIyMDkuMTMzLjUxLjIyNiIsIm5hbWUiOiJKb2huIE1jbGVhbiIsIm9pZCI6IjQyZWViODIyLWEwZmQtNGEyZi1hYjQxLTg5YjAwMzU3NDZkYyIsInBsYXRmIjoiNSIsInB1aWQiOiIxMDAzMDAwMDlCRkQ3RjBFIiwic2NwIjoiVXNlci5SZWFkIiwic3ViIjoiZndEcHpxUFJtZHE0REVWc3BhaDNqQ3dqWXowbGVBTTViaHo3Rk1iTzljMCIsInRpZCI6IjVjODRkYmQ3LTI1N2ItNGNjYS1iMWYxLTI3NGQwNmM4MjkyYSIsInVuaXF1ZV9uYW1lIjoiam9obm1AaXNvZnRzdG9uZS5jb20iLCJ2ZXIiOiIxLjAifQ.m3G1IGR82-49C2qdeDQ1itqK4z7j5muE4Qo-6Hklrr4sdovTvnsyPsoXOYRiQTdFCOWj9qzPX_PM9JE81ngDbALzRFZw2OGj6Z4B0gGQLPvGabRnYW9ezGQsm6xeZSXTL1Vsro5CiEB0kCetTQW_yk3kw6OiDAQi7fwL75EoZcT5GvuUW8KxrhY5TBuppGHuthVF5A49gAGBLAklQgjJmMg2w7PJDfIVkIhqtsFHCkbMNAqG8ueebBWDcndOjYg73QYqTQpZO0teDUVMbdEnIs61_wECzGi8S30PiCh2pVOQmHBRFI8r3wTsYccEN76hKok1Xu0xPUL3OFAlLrzG_w';

const adminUser = 'gadmin@villaosdev.onmicrosoft.com';

var graph = new GraphAPI(AZURE_TENANT, CLIENT_ID, CLIENT_SECRET, null, ACCESS_TOKEN);
// The tenant, clientId, and clientSecret are usually in a configuration file.

// graph.get('users/gadmin@villaosdev.onmicrosoft.com', function (err, user) {
  graph.get('users/gadfmin@isstrainerlive.onmicrosoft.com', function (err, user) {
    if (!err) {
    console.dir(user);
  } else {
    console.log('ERR', err);
  }
});
